DROP SEQUENCE paymentID;
DROP SEQUENCE employeeID;
CREATE SEQUENCE  employeeID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE  paymentID START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE  productID START WITH 9 INCREMENT BY 1;